AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Data Migration
  Amazon EC2 Migration Virtual Machine
Parameters:
  CustomImageID:
    Description: The ID of the AMI to use for the EC2 instance
    Type: "AWS::EC2::Image::Id"
  LocalLocation:
    Description: The IP address range that can be used to connect remotely to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  MigrationVM:
    Type: AWS::EC2::Instance
    Properties: 
    # Required Properties
      ImageId: !Ref CustomImageID
      InstanceType: c6i.xlarge
      SecurityGroups: [!Ref 'MigVMSecurityGroup']
      Tags:
        - Key: "Name"
          Value: "Data Migration VM"
    # Properties
      DisableApiTermination: false
      EbsOptimized: false    
      Monitoring: false
      PropagateTagsToVolumeOnCreation: true
      SourceDestCheck: true
      UserData: 
        Fn::Base64:
          <powershell>
          $PrivateIP = (Get-NetIPAddress | Where-Object {$_.AddressState -eq "Preferred" -and $_.ValidLifetime -lt "24:00:00"}).IPAddress
          $XEPath = "C:\app\Administrator\product\18.0.0\dbhomeXE\network\admin\"

          (Get-Content ($XEPath + "tnsnames.ora")) -Replace '172.31.53.26', $PrivateIP | Set-Content ($XEPath + "tnsnames.ora")
          (Get-Content ($XEPath + "listener.ora")) -Replace '172.31.53.26', $PrivateIP | Set-Content ($XEPath + "listener.ora")

          start-service OracleServiceXE
          start-service OracleOraDB18Home1TNSListener
          </powershell>
      #AdditionalInfo: String
      #Affinity: String
      #AvailabilityZone: String
      #BlockDeviceMappings: 
      #  - BlockDeviceMapping
      #CpuOptions: 
      #  CpuOptions
      #CreditSpecification: 
      #  CreditSpecification
      #ElasticGpuSpecifications: 
      #  - ElasticGpuSpecification
      #ElasticInferenceAccelerators: 
      #  - ElasticInferenceAccelerator
      #EnclaveOptions: 
      #  EnclaveOptions
      #HibernationOptions: 
      #  HibernationOptions
      #HostId: String
      #HostResourceGroupArn: String
      #IamInstanceProfile: String
      #InstanceInitiatedShutdownBehavior: String      
      #Ipv6AddressCount: Integer
      #Ipv6Addresses: 
      #  - InstanceIpv6Address
      #KernelId: String
      #KeyName: String
      #LaunchTemplate: 
      #  LaunchTemplateSpecification
      #LicenseSpecifications: 
      #  - LicenseSpecification
      #NetworkInterfaces: 
      #  - NetworkInterface
      #PlacementGroupName: String
      #PrivateDnsNameOptions: 
      #  PrivateDnsNameOptions
      #PrivateIpAddress: String
      #RamdiskId: String
      #SecurityGroupIds: 
      #  - String
      #SsmAssociations: 
      #  - SsmAssociation
      #SubnetId: String
      #Tags: 
      #  - Tag
      #Tenancy: String
      #UserData: String
      #Volumes: 
      #  - Volume
  MigVMSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Mig VM SecurityGroup
      GroupDescription: Enable remote desktop access via port 
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3389
        ToPort: 3389
        CidrIp: !Ref 'LocalLocation'
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'MigrationVM'
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PublicIp]
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PrivateIp]