AWSTemplateFormatVersion: 2010-09-09
Description: >
  MSP T2 Data Migration
  Amazon EC2 Migration Virtual Machine
Parameters:
  LocalLocation:
    Description: The IP address range that can be used to connect remotely to the EC2 instances
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  MigrationVM:
    Type: AWS::EC2::Instance
    Properties: 
    # Required Properties
      ImageId: ami-0ea7ce8fffb8234e5
    # Properties
      InstanceType: c6i.xlarge    
      DisableApiTermination: false
      EbsOptimized: false    
      Monitoring: false
      PropagateTagsToVolumeOnCreation: true
      SourceDestCheck: true
      Tags:
        - Key: "Name"
          Value: "Migration VM"
      #AdditionalInfo: String
      #Affinity: String
      #AvailabilityZone: String
      #BlockDeviceMappings: 
      #  - BlockDeviceMapping
      #CpuOptions: 
      #  CpuOptions
      #CreditSpecification: 
      #  CreditSpecification
      #ElasticGpuSpecifications: 
      #  - ElasticGpuSpecification
      #ElasticInferenceAccelerators: 
      #  - ElasticInferenceAccelerator
      #EnclaveOptions: 
      #  EnclaveOptions
      #HibernationOptions: 
      #  HibernationOptions
      #HostId: String
      #HostResourceGroupArn: String
      #IamInstanceProfile: String
      #InstanceInitiatedShutdownBehavior: String      
      #Ipv6AddressCount: Integer
      #Ipv6Addresses: 
      #  - InstanceIpv6Address
      #KernelId: String
      #KeyName: String
      #LaunchTemplate: 
      #  LaunchTemplateSpecification
      #LicenseSpecifications: 
      #  - LicenseSpecification
      #NetworkInterfaces: 
      #  - NetworkInterface
      #PlacementGroupName: String
      #PrivateDnsNameOptions: 
      #  PrivateDnsNameOptions
      #PrivateIpAddress: String
      #RamdiskId: String
      #SecurityGroupIds: 
      #  - String
      #SecurityGroups: 
      #  - String
      #SsmAssociations: 
      #  - SsmAssociation
      #SubnetId: String
      #Tags: 
      #  - Tag
      #Tenancy: String
      #UserData: String
      #Volumes: 
      #  - Volume
  MigVMSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable remote desktop access via port 
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3389
        ToPort: 3389
        CidrIp: !Ref 'LocalLocation'
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'MigrationVM'
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PublicDnsName]
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PublicIp]
  PrivateIP:
    Description: Private IP address of the newly created EC2 instance
    Value: !GetAtt [MigrationVM, PrivateIp]
